import logging
from datetime import date

import openpyxl
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from config import COLUMN_SOURCES, DB_COLUMNS

logger = logging.getLogger(__name__)

# ── colour palette ─────────────────────────────────────────────────────────────
_SOURCE_STYLE = {
    # (fill_hex, font_hex, bold, italic)
    "FROM_BROCHURE":       ("4472C4", "FFFFFF", True,  False),
    "FROM_INVENTORY":      ("70AD47", "FFFFFF", True,  False),
    "FROM_PIPELINE":       ("A6A6A6", "FFFFFF", True,  False),
    "INTENTIONALLY_BLANK": ("F2F2F2", "808080", False, True),
}

_SUB_HEADER_LABELS = {
    "FROM_BROCHURE":       "← Extracted from brochure",
    "FROM_INVENTORY":      "← From Master Inventory",
    "FROM_PIPELINE":       "← Generated by pipeline",
    "INTENTIONALLY_BLANK": "← Fill manually",
}

_ROW_LOW_CONFIDENCE_FILL = "FFFF00"

_ACTION_FILL = {
    "NEW":     "C6EFCE",
    "UPDATE":  "FFEB9C",
    "OK":      "FFFFFF",
    "REMOVED": "FFCC99",
    "REVIEW":  "FF0000",
}

_ACTION_SORT_ORDER = {"REVIEW": 0, "NEW": 1, "UPDATE": 2, "REMOVED": 3, "OK": 4}

_TAB2_EXTRA_COLS = ["Action", "Change_Notes", "Match_Score"]

_TAB3_COLS = [
    "Property Name", "Suite", "Size", "Last Verified", "Days on Market",
    "Listing Agency", "Listing Agency in Brochure", "Match_Score", "Possible_Cause",
]

_TAB3_FILL_HEX = "FFCC99"  # orange, same as REMOVED


def build_output_excel(
    brochure_records: list,
    diff_results: list,
    removed_records: list,
    output_path: str,
    run_date: date,
    source_brokerage: str,
) -> str:
    """Writes Excel file. Returns output_path."""
    wb = openpyxl.Workbook()

    ws1 = wb.active
    ws1.title = "Brochure_Extracted"
    _build_tab1(ws1, brochure_records)

    ws2 = wb.create_sheet("Diff_Review")
    _build_tab2(ws2, diff_results)

    ws3 = wb.create_sheet("Removed_Investigate")
    _build_tab3(ws3, removed_records, source_brokerage)

    wb.save(output_path)
    logger.info("Excel saved: %s", output_path)
    return output_path


# ── Tab 1: Brochure_Extracted ─────────────────────────────────────────────────

def _build_tab1(ws, records: list) -> None:
    cols = DB_COLUMNS  # 46 columns

    # Row 1: styled column headers
    for col_idx, col_name in enumerate(cols, start=1):
        source = _col_source(col_name)
        fill_hex, font_hex, bold, italic = _SOURCE_STYLE[source]
        cell = ws.cell(row=1, column=col_idx, value=col_name)
        _style_cell(cell, fill_hex=fill_hex, font_hex=font_hex, bold=bold, italic=italic,
                    align="center", wrap=True)

    # Row 2: merged sub-header labels per contiguous source group
    for start_col, end_col, source in _contiguous_runs(cols):
        fill_hex, font_hex, _, _ = _SOURCE_STYLE[source]
        label = _SUB_HEADER_LABELS[source]
        if start_col < end_col:
            ws.merge_cells(
                start_row=2, start_column=start_col,
                end_row=2, end_column=end_col,
            )
        cell = ws.cell(row=2, column=start_col, value=label)
        _style_cell(cell, fill_hex=fill_hex, font_hex=font_hex, italic=True, align="center")

    # Data rows (start at row 3)
    for row_idx, record in enumerate(records, start=3):
        confidence = str(record.get("Extraction_Confidence", "")).lower()
        row_fill = _make_fill(_ROW_LOW_CONFIDENCE_FILL) if confidence == "low" else None
        for col_idx, col_name in enumerate(cols, start=1):
            val = record.get(col_name)
            cell = ws.cell(row=row_idx, column=col_idx, value=val)
            if row_fill:
                cell.fill = row_fill

    ws.freeze_panes = "A3"
    last_data_row = max(len(records) + 2, 2)
    ws.auto_filter.ref = f"A1:{get_column_letter(len(cols))}{last_data_row}"
    _auto_fit(ws)


# ── Tab 2: Diff_Review ────────────────────────────────────────────────────────

def _build_tab2(ws, diff_results: list) -> None:
    sorted_rows = sorted(
        diff_results,
        key=lambda r: _ACTION_SORT_ORDER.get(r.get("Action", "OK"), 4),
    )
    all_cols = _TAB2_EXTRA_COLS + DB_COLUMNS

    # Row 1: headers
    for col_idx, col_name in enumerate(all_cols, start=1):
        if col_name in _TAB2_EXTRA_COLS:
            cell = ws.cell(row=1, column=col_idx, value=col_name)
            _style_cell(cell, fill_hex="D9D9D9", font_hex="000000", bold=True, align="center")
        else:
            source = _col_source(col_name)
            fill_hex, font_hex, bold, italic = _SOURCE_STYLE[source]
            cell = ws.cell(row=1, column=col_idx, value=col_name)
            _style_cell(cell, fill_hex=fill_hex, font_hex=font_hex, bold=bold, align="center",
                        wrap=True)

    # Data rows
    for row_idx, record in enumerate(sorted_rows, start=2):
        action = record.get("Action", "")
        action_hex = _ACTION_FILL.get(action, "FFFFFF")
        row_fill = _make_fill(action_hex) if action_hex != "FFFFFF" else None
        for col_idx, col_name in enumerate(all_cols, start=1):
            val = record.get(col_name)
            cell = ws.cell(row=row_idx, column=col_idx, value=val)
            if row_fill:
                cell.fill = row_fill

    # Freeze cols A-C (first 3) and row 1 → pane anchor = D2
    ws.freeze_panes = "D2"
    last_data_row = max(len(sorted_rows) + 1, 1)
    ws.auto_filter.ref = f"A1:{get_column_letter(len(all_cols))}{last_data_row}"
    _auto_fit(ws)


# ── Tab 3: Removed_Investigate ────────────────────────────────────────────────

def _build_tab3(ws, removed_records: list, source_brokerage: str) -> None:
    from modules.comparator import infer_possible_cause

    orange_fill = _make_fill(_TAB3_FILL_HEX)

    # Header row
    for col_idx, col_name in enumerate(_TAB3_COLS, start=1):
        cell = ws.cell(row=1, column=col_idx, value=col_name)
        _style_cell(cell, fill_hex=_TAB3_FILL_HEX, font_hex="000000", bold=True, align="center")

    # Data rows (all orange)
    for row_idx, record in enumerate(removed_records, start=2):
        possible_cause = infer_possible_cause(record, source_brokerage)
        row_data = {
            "Property Name":               record.get("Property Name"),
            "Suite":                       record.get("Suite"),
            "Size":                        record.get("Size"),
            "Last Verified":               record.get("Last Verified"),
            "Days on Market":              record.get("Days on Market"),
            "Listing Agency":              record.get("Listing Agency"),
            "Listing Agency in Brochure":  source_brokerage,
            "Match_Score":                 record.get("Match_Score"),
            "Possible_Cause":              possible_cause,
        }
        for col_idx, col_name in enumerate(_TAB3_COLS, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=row_data.get(col_name))
            cell.fill = orange_fill

    _auto_fit(ws)


# ── shared helpers ─────────────────────────────────────────────────────────────

def _col_source(col_name: str) -> str:
    for source, cols in COLUMN_SOURCES.items():
        if col_name in cols:
            return source
    return "FROM_PIPELINE"


def _make_fill(hex_color: str) -> PatternFill:
    return PatternFill(start_color=hex_color, end_color=hex_color, fill_type="solid")


def _style_cell(
    cell,
    fill_hex: str = None,
    font_hex: str = "000000",
    bold: bool = False,
    italic: bool = False,
    align: str = None,
    wrap: bool = False,
) -> None:
    if fill_hex:
        cell.fill = _make_fill(fill_hex)
    cell.font = Font(bold=bold, italic=italic, color=font_hex)
    if align:
        cell.alignment = Alignment(
            horizontal=align, vertical="center", wrap_text=wrap
        )


def _contiguous_runs(cols: list) -> list:
    """Return [(start_col_1idx, end_col_1idx, source), ...] for consecutive same-source groups."""
    if not cols:
        return []
    runs = []
    current_source = _col_source(cols[0])
    run_start = 1
    for i, col in enumerate(cols[1:], start=2):
        source = _col_source(col)
        if source != current_source:
            runs.append((run_start, i - 1, current_source))
            current_source = source
            run_start = i
    runs.append((run_start, len(cols), current_source))
    return runs


def _auto_fit(ws, max_width: int = 40) -> None:
    """Approximate column auto-fit based on max character length."""
    for col in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col[0].column)
        for cell in col:
            if cell.value is not None:
                max_len = max(max_len, len(str(cell.value)))
        ws.column_dimensions[col_letter].width = min(max_len + 2, max_width)
